# SPDX-License-Identifier: BSD-3-Clause */

# Copyright (c) 2020 Rockchip Electronics Co., Ltd.

PROJECT		:= Swallow
CPU		:= -march=rv32imac -mabi=ilp32 -DARCH_RISCV

include ../../common/GCC/riscv.mk
